AllCops:
  Excludes:
    - Berksfile
    - recipes/basic.rb
    - attributes/*.rb
    - config/initializers/*.rb
    - config/environments/production.rb
    - db/*.rb
    - db/migrate/*.rb

Documentation:
  Enabled: false

# Customize rules
Metrics/LineLength:
  Max: 95

MethodLength:
  Max: 35

Metrics/AbcSize:
   Enabled: false

BlockLength:
  Max: 70

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
  Exclude:
    - 'Gemfile'
